//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class DefaultAPI {
    /**
     Authorize user
     
     - parameter inlineObject: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func login(inlineObject: InlineObject, completion: @escaping ((_ data: AuthorizedUser?,_ error: Error?) -> Void)) {
        loginWithRequestBuilder(inlineObject: inlineObject).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Authorize user
     - POST /auth
     - parameter inlineObject: (body)  
     - returns: RequestBuilder<AuthorizedUser> 
     */
    open class func loginWithRequestBuilder(inlineObject: InlineObject) -> RequestBuilder<AuthorizedUser> {
        let path = "/auth"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inlineObject)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<AuthorizedUser>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
