//
// EmployeeDepartment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct EmployeeDepartment: Codable {

    public var id: Int?
    public var name: String?
    public var alternativeName: String?

    public init(id: Int?, name: String?, alternativeName: String?) {
        self.id = id
        self.name = name
        self.alternativeName = alternativeName
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case alternativeName = "alternative_name"
    }


}

