//
// EmployeeLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct EmployeeLocation: Codable {

    public var id: Int?
    public var name: String?
    public var isActive: Bool?

    public init(id: Int?, name: String?, isActive: Bool?) {
        self.id = id
        self.name = name
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case isActive = "is_active"
    }


}

