//
// EmployeeTitle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct EmployeeTitle: Codable {

    public var id: Int?
    public var name: String?
    public var alternativeName: String?
    public var department: Int?

    public init(id: Int?, name: String?, alternativeName: String?, department: Int?) {
        self.id = id
        self.name = name
        self.alternativeName = alternativeName
        self.department = department
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case alternativeName = "alternative_name"
        case department
    }


}

