//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineObject: Codable {

    public var username: String
    public var password: String

    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }


}

