//
// ReportsTo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ReportsTo: Codable {

    public var id: Int?
    public var email: String?
    public var fullName: String?

    public init(id: Int?, email: String?, fullName: String?) {
        self.id = id
        self.email = email
        self.fullName = fullName
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case email
        case fullName = "full_name"
    }


}

