//
// Skill.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Skill: Codable {

    public var id: Int?
    public var measured: String?
    public var name: String?
    public var treePath: String?
    public var isKeySkill: Bool?

    public init(id: Int?, measured: String?, name: String?, treePath: String?, isKeySkill: Bool?) {
        self.id = id
        self.measured = measured
        self.name = name
        self.treePath = treePath
        self.isKeySkill = isKeySkill
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case measured
        case name
        case treePath = "tree_path"
        case isKeySkill = "is_key_skill"
    }


}

